# Projeto Python IA: Inteligência Artificial e Previsões

### Case: Score de Crédito dos Clientes

Um banco fictício pediu ajuda para conseguir definir o score de crédito dos clientes. É preciso analisar todos os clientes do banco e, com base nessa análise, criar um modelo de IA que consiga ler as informações do cliente e dizer automaticamente o score de crédito dele: Ruim, Ok, Bom (Poor, Standard, Good)

Este projeto visa explorar as funções de manipulação de dados e tabelas com a biblioteca Pandas e a criação de modelos de IA com a biblioteca Scikit-Learn.

In [ ]:
#  Passo 1

#  Importação do Pandas e da base de dados
import pandas as pd
tabela = pd.read_csv("clientes.csv")

#  Exibindo a base de dados em forma de tabela
display(tabela)

#  Observando os campos, podemos notar que existem informações importantes que vão ajudar no aprenidizado da IA, como gastos, atrasos, salário e um score de crédito, que é nada menos do que queremos prever para novos clientes.

       id_cliente  mes  ...  emprestimo_credito emprestimo_estudantil
0            3392    1  ...                   1                     0
1            3392    2  ...                   1                     0
2            3392    3  ...                   1                     0
3            3392    4  ...                   1                     0
4            3392    5  ...                   1                     0
...           ...  ...  ...                 ...                   ...
99995       37932    4  ...                   0                     1
99996       37932    5  ...                   0                     1
99997       37932    6  ...                   0                     1
99998       37932    7  ...                   0                     1
99999       37932    8  ...                   0                     1

[100000 rows x 25 columns]

In [ ]:
#  Passo 2

#  O segundo passo preparar nossa base de dados para a IA interpretar, já que ela interpreta apenas números. 
#  Pensando nisso, precisamos verificar como estão os dados da nossa tabela e o comando abaixo nos ajuda com isso. 
display(tabela.info())

#  Com as informações visíveis, conseguimos notar que os dados estão organizados adequadamente, e que os tipos de dados de cada campo estão coerentes.
#  No entanto, existem algumas colunas em que os dados são do tipo 'object', ou seja, um texto. Sendo assim, não compreendidos pelos mopdelos de IA, então precisamos tratar isso primeiramente.
#  Com base nas informações da tabela, temos 4 colunas que não tem dados numéricos. São elas 'profissao', 'mix_credito', 'comportamento_pagamento' e 'score_credito'. 
#  A última coluna, 'score_credito' é a informação que queremos prever, então não tem problema não ser do tipo numérico.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  object
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  object
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  object
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(7), object(4)
memory usage: 19.1+ MB

None

In [ ]:
#  O desafio nessa etapa é: Transformar os dados textuais em numéricos para que possam ser compreendidos pela IA. 
#  Para tal tarefa, temos o processo de LabelEncoder, que atribui um número a um texto expecífico. 
#  Na prática, cada profissão será substituída por um número. Por exemplo: Cientista -> 1, Mecanico -> 2, Motorista -> 3.

#  Importando o LabelEncoder do scikit-learn.
from sklearn.preprocessing import LabelEncoder

#  Definindo codificadores que tranformação os dados de uma coluna em números.
codificador1 = LabelEncoder()
codificador2 = LabelEncoder()
codificador3 = LabelEncoder()

#  É necessário criar 3 codificadores, pois temos 3 colunas que serão convertidas. Cada codificador sendo responsável por uma coluna.

#  Para a tabela "profissao":
tabela["profissao"] = codificador1.fit_transform(tabela["profissao"])

#  Para a tabela "mix_credito":
tabela["mix_credito"] = codificador2.fit_transform(tabela["mix_credito"])

#  Para a tabela "comportamento_pagamento":
tabela["comportamento_pagamento"] = codificador3.fit_transform(tabela["comportamento_pagamento"])

#  Explicando a lógica do método: Estou pegando cada coluna que quero mudar e atribuindo um novo valor que é o valor antigo, porém com o método .fit_transform aplicado. 

# O método fit_transform pega os valores da coluna, ajusta/define um número para eles (fit) e transforma os campos da coluna (transform), substintuindo assim os dados de texto por números.

#  Exibindo as informações da tabela novamente, após processamento.
display(tabela.info())

#  Logo, podemos ver que os tipos de dados das colunas que eu queria trocar, foram substituídos por dados do tipo "int", ou seja, um número inteiro.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  int64
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  int64
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  int64
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(10), object(1)
memory usage: 19.1+ MB

None

In [ ]:
#  A próxima etapa ainda é sobre preparar os dados para treinar a IA. 
#  É preciso agora separar as informações da base de dados, que geralmente se faz em X e Y. Sendo Y a informação que eu quero prever e X todas as outras informações. Y, por convenção, sempre será a coluna que a IA deverá fazer a previsão. X sempre serão as outras colunas.
#  Nesse caso:
y = tabela["score_credito"]
x = tabela.drop(columns=["score_credito", "id_cliente"])
#  O método .drop é o que permite retirar uma ou mais colunas que queremos considerar para essa variável. Garante a permanência apenas dos campos relevantes.

#  A segunda separação necessária é a dos dados de treino e dados de teste.
#  A função que faz isso pra gente é a train_test_split. Ela separa automaticamente uma parte da base de dados para treino e outra parte para teste. 
#  Lembrando que Y é sempre o dado que eu quero prever e X os outros dados.
#  Com o train_test_split, teremos então: o "y de treino", que vai ser o score_credito dos clientes existentes e o "y de teste", que funcionará como um gabarito para testar a IA. Ou seja, clientes a IA não vai conseguir visualizar score_credito e vai tentar prever qual é, para então depois termos uma comparação e sabrer a precisão da previsão da IA. 
#  70% dos dados devem ser para treino, e 30% para teste. Não é uma regra, mas é o recomendado apra a maioria dos casos. 

from sklearn.model_selection import train_test_split 
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3)

#  Entendendo a lógica do método: Estou criando variáveis chamadas 'x_treino', 'x_teste', 'y_treino' e 'y_teste' usando as variaveis definidas anteriormente (x e y). Com o 'test_size=0.3' estou separando 30% dos meus dados para teste, ou seja, vai ser aquela parte dos dados que a IA não vai saber a resposta na hora de tentar fazer a previsão.

In [15]:
#  Agora é hora de criar o modelo de IA, e na maioria dos casos, devemos seguin 3 passos básicos.

#  Primeiro passo: Importar o modelo.
#  Vou testar dois modelos e ver qual se sai melhor nos testes. 

#  Modelo de árvore de decisão -> RandomForest
from sklearn.ensemble import RandomForestClassifier

#  Modelo de vizinhos próximos -> KNN 
from sklearn.neighbors import KNeighborsClassifier

#  Segundo passo: Criar Modelo.
modelo_arvoredecisao = RandomForestClassifier()

modelo_knn = KNeighborsClassifier()

#  Terceiro passo: Treinar Modelo.
modelo_arvoredecisao.fit(x_treino, y_treino)

modelo_knn.fit(x_treino, y_treino)

KNeighborsClassifier()

In [ ]:
#  Passo 4: Escolher o melhor modelo

#  Realizar os testes dos dois modelos de IA
#  O método 'predict' é usado para realizar a previsão
previsao_arvordedecisao = modelo_arvoredecisao.predict(x_teste)
previsao_knn = modelo_knn.predict(x_teste)

#  Calcular a acurácia dos modelos
from sklearn.metrics import accuracy_score

#  Aqui estamos exibindo a porcentagem da precisão de cada modelo
#  Com o método Accuracy Score, passamos nossos dados de teste, e a previsão de cada modelo (definida nas variáveis acima) como parâmetros
display(accuracy_score(y_teste, previsao_arvordedecisao))
display(accuracy_score(y_teste, previsao_knn))

#  Com isso vemos que ao comparar os dados de teste (gabarito da nossa IA) temos o primeiro modelo que teve 82.30% de precisão e o outro que teve 73,35% de precisão. De acordo com o desafio dessa empresa que seria definir um perfil de crédito de novos clientes, o primeiro percentual é o suficiente. 
#  Caso desejamos aumentar essa precisão, podemos aumentar a quantidade de dados de treino ou então testar outros modelos de IA.

0.8230666666666666

0.7335

In [ ]:
#  Passo 5: Usar o modelo de árvore de decisão para fazer a previsão de score de crédito dos clientes novos

#  Importação e visualização da tabela com os clientes novos
tabela_nova = pd.read_csv("novos_clientes.csv")

display(tabela_nova)

   mes  idade  ... emprestimo_credito  emprestimo_estudantil
0    1   31.0  ...                  0                      0
1    4   32.0  ...                  0                      1
2    2   48.0  ...                  1                      0

[3 rows x 23 columns]

In [21]:
#  Codificar os dados que não são numéricos

#  Para a tabela "profissao":
tabela_nova["profissao"] = codificador1.fit_transform(tabela_nova["profissao"])

#  Para a tabela "mix_credito":
tabela_nova["mix_credito"] = codificador2.fit_transform(tabela_nova["mix_credito"])

#  Para a tabela "comportamento_pagamento":
tabela_nova["comportamento_pagamento"] = codificador3.fit_transform(tabela_nova["comportamento_pagamento"])

display(tabela_nova["profissao"])

0    1
1    0
2    1
Name: profissao, dtype: int64

In [1]:
#  Fazer a previsao com a IA

previsao = modelo_arvoredecisao.predict(tabela_nova)

display(previsao)

#  Com isso temos o resultado da análise de dados feitos pelo modelo de inteligência artificial escolhido. 
#  Temos para os novos clientes respectivamente um score de crédito 'poor'(ruim), 'good'(bom) e 'standard'(ok)
#  E com essa informação, a instituição financeira consegue ter uma base para definir se é um cliente que terá crédito aprovado ou não e o quanto de limite poderá oferecer para ele.

NameError: name 'modelo_arvoredecisao' is not defined